#File for specifying run informtion to pipeline.py
#Stages should hold the details of each stage which can be called
#by the pipeline. Each stage must contain a command definition.


stages:
    description: 'Run from Illumina'
    genome_build: 'ucsc.hg19'
    algorithm:
        aligner:
            command: 'bwa aln -f %(out)s -t %(threads)d %(encodingflag)s %(ref)s %(seq)s'
        indexer:
            command: 'bwa index -a %(algorithm)s -p %(prefix)s %(seq)s'
        samse:
            command: 'bwa samse -f %(out)s %(meta)s %(ref)s %(align)s %(seq)s'
        sampe:
            command: 'bwa sampe -f %(out)s %(meta)s %(ref)s %(align1)s %(align2)s %(seq1)s %(seq2)s'
        sam2bam:
            command: 'java %(jvmoptions)s -jar %(picarddir)s/SortSam.jar SO=coordinate INPUT=%(sam)s OUTPUT=%(out)s VALIDATION_STRINGENCY=LENIENT CREATE_INDEX=true'
        markduplicates:
            command: 'java %(jvmoptions)s -jar %(picarddir)s/MarkDuplicates.jar INPUT=%(bam)s OUTPUT=%(out)s METRICS_FILE=%(log)s CREATE_INDEX=true VALIDATION_STRINGENCY=LENIENT'
        realigner:
            command: 'java %(jvmoptions)s -jar %(gatkdir)s/GenomeAnalysisTK.jar -T RealignerTargetCreator -R %(ref)s -o %(out)s -I %(bam)s'
        indelrealigner:
            command: 'java %(jvmoptions)s -jar %(gatkdir)s/GenomeAnalysisTK.jar -I %(bam)s -R %(ref)s -T IndelRealigner -targetIntervals %(intervals)s -o %(out)s'
        fixmates:
            command: 'java %(jvmoptions)s -jar %(picarddir)s/FixMateInformation.jar INPUT=%(bam)s OUTPUT=%(out)s SO=coordinate CREATE_INDEX=true VALIDATION_STRINGENCY=LENIENT'
        bamindexer:
            command: '%samdir/samtools index %bam'
        countcovariates:
            command: 'java %(jvmoptions)s -jar %(gatkdir)s/GenomeAnalysisTK.jar -l INFO -T BaseRecalibrator -I %(bam)s -R %(ref)s -knownSites %(dbsnp)s -cov QualityScoreCovariate -cov CycleCovariate -cov ContextCovariate -cov ReadGroupCovariate -o %(out)s'
        recaltabulate:
            command: 'java %(jvmoptions)s -jar %(gatkdir)s/GenomeAnalysisTK.jar -T PrintReads -I %(bam)s -R %(ref)s -BQSR %(recalfile)s -o %(out)s'
        callSNPs:
            command: 'java %jvmoptions -jar %gatkdir/GenomeAnalysisTK.jar -nt %threads -R %ref -I %bam --dbsnp %dbsnp -T HaplotypeCaller -stand_emit_conf %sec  -stand_call_conf %scf -dcov %dcov -glm SNP --genotyping_mode DISCOVERY --max_alternate_alleles %alleles -o %out'
        filterSNPs:
            command: "java %jvmoptions -jar %gatkdir/GenomeAnalysisTK.jar -nt %threads -T VariantFiltration -R %ref --variant %vcf --filterExpression '%expression' --output_mode EMIT_ALL_SITES -o %out"
